<?php

namespace Entretien\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Entretien\NewsBundle\Entity\Advert;

/**
 * AdvertRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function createNew()
    {
        return new Advert();
    }

    public function findOrderByDate($limit = 10)
    {
        return $this->createQueryBuilder('a')
            ->setMaxResults($limit)
            ->orderBy('a.created', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
