<?php

namespace Entretien\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Entretien\NewsBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function createNew()
	{
		return new Comment();
	}

	public function countComments($advert)
	{
		return $this->createQueryBuilder('c')
		    ->select('COUNT(c)')
			->where('c.advert = :advert')
			->setParameter('advert', $advert)
			->getQuery()
			->getSingleScalarResult();
	}
}
